filter:
    excluded_paths: [docs/*, examples/*, tests/*]

checks:
    php: true

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
        php: "5.6"
        mysql: "5.5"
        postgresql: false
        mongodb: false
        redis: false
        neo4j: false
        rabbitmq: false
    dependencies:
        before:
            - sudo service start mysql || true
            - mysql -e "CREATE DATABASE IF NOT EXISTS testsimplecache"
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=/tmp/coverage.xml'
                coverage:
                    file: '/tmp/coverage.xml'
                    format: 'clover'
